services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai_knowledge_postgres

    environment:
      POSTGRES_DB: knowledge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d knowledge_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: ai_knowledge_redis

    ports:
      - "6379:6379"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build: .
    container_name: ai_knowledge_api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/knowledge_db
      REDIS_URL: redis://redis:6379/0

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}

      MAX_COSINE_DISTANCE: ${MAX_COSINE_DISTANCE:-0.60}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-300}

      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-10}
      RATE_LIMIT_WINDOW_SECONDS: ${RATE_LIMIT_WINDOW_SECONDS:-60}

    depends_on:

      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    volumes:
      - ./data:/app/data

    command: >
      sh -c "
      python -m app.init_db &&
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      "


volumes:
  postgres_data: